### ISSUE TITLE
ID count per server

### ISSUE THREAD

**Issue by PenguinKnight303** [bumblepie/haikubot#41] opened 2019-03-07 19:20 UTC
It's no fun having to guess at IDs hoping they're from your server.

**Comment by bumblepie** [comment] 2019-03-09 04:46
I think this would be better served by giving search functionality honestly

**Comment by PenguinKnight303** [comment] 2019-03-09 04:50
I kinda like being able to roll through some at random though. Maybe pair search with a random haiku function.

**Comment by bumblepie** [comment] 2019-03-09 04:53
yep, fetching a random haiku from the server is definitely a valid use case, so I think having a command for that would be nice.

**Comment by PenguinKnight303** [comment] 2019-03-09 04:57
Search + Random would mean you rarely need by ID so yeah fair enough. Maybe ID should be random rather than sequential in that case?

**Comment by bumblepie** [comment] 2019-03-20 08:12
I'm gonna close this issue and open two new issues for search and random commands respectively since they provide the expected behaviour

**Closed by bumblepie** 2019-03-20 08:12 UTC

**Comment by bumblepie** [comment] 2019-03-20 08:17
Opened #48 and #47
